version: '3.7'

# Run previously:
# `docker pull mongo`
# './gradlew jibDockerBuild' at project directory

services:
  mongo:
    #container_name: coffee-mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    hostname: mongo
    networks:
      - overlay

  boot:
    #container_name: coffe-boot
    image: codesolt/boot-mongo:0.0.1
    depends_on:
      - mongo
    ports:
      - 8080:8080
      - 5005:5005
    restart: on-failure
    networks:
      - overlay

networks:
  overlay:
    driver: bridge